### ISSUE TITLE
Package conflict with web3Swift

### ISSUE THREAD

**Issue by simonmcl** [torusresearch/torus-direct-swift-sdk#9]
Trying to import this swift package into a newly build swift package version of my library, and i'm getting a target conflict. I'm also using `secp256k1` in my package, which is getting marked as a duplicate because `web3Swift` also exports a target called `secp256k1`.

I can see in the fork you are using, that the /develop branch has re-named it to something else, but this package isn't making use of that change: https://github.com/rathishubham7/web3swift/blob/develop/Package.swift

Also note there are a few warnings from `swift-nio-zlib-support` about a target being ignored. Apple themselves say that package is no longer supported a recommend migrating to another option: https://github.com/apple/swift-nio-zlib-support/issues/4 . You may need to look into the dependency chain on this library and choose some alternatives

**Comment by rathishubham7** [comment]
This has been fixed in 1.0.1.
